### PR TITLE
fixed compatibility issues with cordova-android@7.0.0

### LINKED ISSUE #188: Crosswalk with Cordova-Android 7.0 -> Failed to install 'cordova-plugin-crosswalk-webview': Error: Unhandled "error" event. (Parsing platforms/android/res/xml/config.xml failed)
Hey guys,

I'm getting this error since few days.

	Discovered plugin "cordova-plugin-crosswalk-webview" in config.xml. Adding it to the project
	Installing "cordova-plugin-crosswalk-webview" for android
	Subproject Path: CordovaLib
	Subproject Path: app
			After much discussion and analysis of the market, we have decided to discontinue support for Android 4.0 (ICS) in Crosswalk starting with version 20.
			So the minSdkVersion of Cordova project is configured to 16 by default.
		
	Failed to install 'cordova-plugin-crosswalk-webview': Error: Unhandled "error" event. (Parsing /bitrise/src/platforms/android/res/xml/config.xml failed)
		at EventEmitter.emit (events.js:186:19)
		at EventEmitter.module.exports.emit (/usr/lib/node_modules/cordova/node_modules/cordova-common/src/events.js:71:17)
		at new ConfigParser (/usr/lib/node_modules/cordova/node_modules/cordova-common/src/ConfigParser/ConfigParser.js:34:16)
		at new module.exports (/bitrise/src/plugins/cordova-plugin-crosswalk-webview/hooks/update_config.js:37:25)
		at module.exports (/bitrise/src/plugins/cordova-plugin-crosswalk-webview/hooks/after_plugin_install/000-shared_mode_special.js:8:24)
		at runScriptViaModuleLoader (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:18)
		at runScript (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:164:16)
		at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:20
		at _fulfilled (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
		at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
	Failed to restore plugin "cordova-plugin-crosswalk-webview" from config.xml. You might need to try adding it again. Error: Error: Unhandled "error" event. (Parsing /bitrise/src/platforms/android/res/xml/config.xml failed)

I'm using newest Android Cordova 7.0.0 and also tried with 6.3.

Do you know why this fails?

If I install this on my local computer (not on linux build machine) then everything works fine.

### PR DESCRIPTION
**Pull request by kaynz**
fixes #188, credits to @philoskim

### CODE REVIEW

**Comment by jpike88** [comment]
confirmed works for me on cordova@8.0.0

**Comment by rakuco** [comment]
Doesn't this break older releases which worked with the existing paths?

**Comment by jpike88** [comment]
Unfortunately, yes.

Perhaps some symlinks might help

**Comment by kaynz** [comment]
@fujunwei Any chance to get this merged?

**Comment by baleboy** [comment]
@kaynz it is mentioned above that this PR will break integration with older Cordova releases, so that should be addressed first.

**Comment by kaynz** [comment]
@baleboy Done. I've updated the PR.

File: hooks/update_config.js [hunk 1]
```diff
@@ -21,18 +21,22 @@ module.exports = function(context) {
...
         pluginConfigurationFile = path.join(context.opts.plugin.dir, 'plugin.xml'),
-        androidPlatformDir = path.join(context.opts.projectRoot,
-            'platforms', 'android'),
-        projectConfigurationFile = path.join(context.opts.projectRoot,
-            'config.xml'),
-        platformConfigurationFile = path.join(androidPlatformDir,
-            'res', 'xml', 'config.xml'),
-        projectManifestFile = path.join(androidPlatformDir,
-            'AndroidManifest.xml'),
+        androidPlatformDir = path.join(context.opts.projectRoot, 'platforms', 'android'),
```
Comment (rakuco) [inline hooks/update_config.js]: `androidPlatformDir`, `projectConfigurationFile` and `projectManifestFile` have the same values they did before, so could you revert the style changes?

File: platforms/android/xwalk.gradle [hunk 2]
```diff
@@ -29,7 +29,18 @@ def DEFAULT_MIN_SDK_VERSION = 14
 
 def getConfigPreference(name) {
     name = name.toLowerCase()
-    def xml = file("res/xml/config.xml").getText()
+
+    def xml
+
+    // cordova-android >= 7.0.0
+    xml = file("src/main/res/xml/config.xml")
```
Comment (rakuco) [inline platforms/android/xwalk.gradle]: What if you do something like

```
def configXmlLocations = [
    // cordova-android >= 7.0.0
    "src/main/res/xml/config.xml",
    // cordova-android < 7.0.0
    "res/xml/config.xml"
]
configXml = configXmlLocations.find {
    return file(it).exists()
}
xml = file(configXml).getText()
```

File: hooks/update_config.js (hunk 1 above)
Comment (kaynz) [reply hooks/update_config.js]: Done.

File: platforms/android/xwalk.gradle (hunk 2 above)
Comment (kaynz) [reply platforms/android/xwalk.gradle]: It's less readable.

Comment (rakuco) [reply platforms/android/xwalk.gradle]: I disagree. Right now you're using the same variable with different meanings, with calls to `file()` in different levels of indentation. You don't even need to follow what I said as-is (my Gradle knowledge is... modest), but the existing code could be improved.

Comment (kaynz) [reply platforms/android/xwalk.gradle]: Pushed another one.

File: hooks/update_config.js [hunk 3]
```diff
@@ -23,16 +23,23 @@ module.exports = function(context) {
         pluginConfigurationFile = path.join(context.opts.plugin.dir, 'plugin.xml'),
         androidPlatformDir = path.join(context.opts.projectRoot,
             'platforms', 'android'),
-        projectConfigurationFile = path.join(context.opts.projectRoot,
-            'config.xml'),
+        projectConfigurationFile,
```
Comment (rakuco) [inline hooks/update_config.js]: Why was this change made? I don't see `projectConfigurationFile` being set anywhere now.

File: platforms/android/xwalk.gradle [hunk 4]
```diff
@@ -29,7 +29,18 @@ def DEFAULT_MIN_SDK_VERSION = 14
 
 def getConfigPreference(name) {
     name = name.toLowerCase()
-    def xml = file("res/xml/config.xml").getText()
+
+    def xml
+
+    // cordova-android >= 7.0.0
+    def configFile = file("src/main/res/xml/config.xml")
```
Comment (rakuco) [inline platforms/android/xwalk.gradle]: I can see you're no longer using `xml` for multiple purposes. However, I still believe the style here doesn't look as "even" as it could (`configFile` is used in only one of the branches, for example). My suggestion of iterating through the possible location remains.

Comment (kaynz) [reply platforms/android/xwalk.gradle]: Feel free:

2018-01-15-091544_162x50_escrotum

**Comment by rakuco** [comment]
Thank you.
